Build script updates

diff --git a/scripts/build-common b/scripts/build-common
--- a/scripts/build-common
+++ b/scripts/build-common
@@ -1,10 +1,10 @@
 #!/bin/bash
 set -e
 
-: ${BUILD:=$(readlink -f ./build)}
-: ${ARTIFACTS:=$(readlink -f ./assets)}
-: ${CONFIG:=$(readlink -f ./config)}
-: ${DIST:=$(readlink -f ./dist)}
+: ${ARTIFACTS:=$(pwd)/assets}
+: ${BUILD:=$(pwd)/build}
+: ${CONFIG:=$(pwd)/config}
+: ${DIST:=$(pwd)/dist}
 
 BUILDROOT=buildroot-2014.11.tar.bz2
 DOCKER_FILE=${CONFIG}/.dockerfile
@@ -37,8 +37,8 @@ write_base()
 
     mkdir -p $(dirname ${DOCKER_FILE})
 
-    cat > ${DOCKER_FILE} << "EOF"
-FROM ubuntu:14.04.1
+    cat > ${DOCKER_FILE} << EOF
+FROM ${DOCKER_BASE:=ubuntu:14.04.1}
 ENV TERM xterm
 WORKDIR /source
 CMD ["/source/scripts/install"]
@@ -49,43 +49,35 @@ EOF
 
 run()
 {
-    local run=true
     local content
 
     while [ $# -gt 1 ]; do
         case $1 in
-            --no-docker)
-                if [ "$DOCKER_BUILD" = "true" ]; then
-                    run=false
-                fi
-                ;;
             --assets)
                 shift 1
+                if [ -e "$1" ]; then
                 content="$content\nCOPY $1 /source/$1"
+                else
+                    content="$content\nCOPY $1 /source/"
+                fi
                 ;;
         esac
 
         shift 1
     done
 
-    if [ "$DOCKER_BUILD" = "true" ]; then
-        write_base
-        if [ -n "$content" ]; then
-            echo -e "$content" >> ${DOCKER_FILE}
-        fi
-        echo -e "\nCOPY $1 /source/$1" >> ${DOCKER_FILE}
-        echo -e "RUN /source/$1" >> ${DOCKER_FILE}
-    elif [ "$run" != "false" ]; then
-        $1
+    write_base
+    if [ -n "$content" ]; then
+        echo -e "$content" >> ${DOCKER_FILE}
+    fi
+    if [ -n "$1" ]; then
+    echo -e "\nCOPY $1 /source/$1" >> ${DOCKER_FILE}
+    echo -e "RUN /source/$1" >> ${DOCKER_FILE}
     fi
 }
 
 finish()
 {
-    if [ "$DOCKER_BUILD" != "true" ]; then
-        return
-    fi
-
     local cmd="docker build -t ${DOCKER_IMAGE} -f ${DOCKER_FILE} ."
     echo Running $cmd
     echo Pwd $(pwd)
@@ -93,4 +85,41 @@ finish()
     cat ${DOCKER_FILE}
 
     $cmd
+}
+
+reset_docker_build()
+{
+    BASE_WRITTEN=false
+}
+
+check()
+{
+    local hash=$1
+    local file=$2
+
+    if [ ! -e "$file" ]; then
+        return 1
+    fi
+
+    CURRENT=$(sha1sum $file | awk '{print $1}')
+
+    [ "$hash" = "$CURRENT" ]
+}
+
+download()
+{
+    mkdir -p ${ARTIFACTS}
+
+    local url=$2
+    local file=${ARTIFACTS}/$(basename $2)
+    local hash=$1
+
+    if ! check $hash $file; then
+        curl -sL $url > $file
+    fi
+
+    if ! check $hash $file; then
+        echo "ERROR: $file does not match checksum $hash, got $CURRENT" 1>&2
+        return 1
+    fi
 }
