Multi-arch build
with dapper

diff --git a/scripts/build-busybox b/scripts/build-busybox
--- a/scripts/build-busybox
+++ b/scripts/build-busybox
@@ -3,6 +3,46 @@ set -e
 
 cd $(dirname $0)/..
 
-. scripts/build-common
+: ${ARTIFACTS:=$(pwd)/assets}
+: ${BUILD:=$(pwd)/build}
 
-busybox_install ${CONFIG}/buildroot-config ${CONFIG}/busybox-dynamic.config ${DIST}
+busybox_install()
+{
+    local conf=$1
+    local bbconf=$2
+    local target=$3
+
+    if [ "$#" = "2" ]; then
+        target=$2
+        bbconf=
+    fi
+
+    mkdir -p ${target}
+
+    mkdir -p ${BUILD}
+    cd ${BUILD}
+
+    local buildroot=$(ls -1 ${ARTIFACTS}/buildroot-*.tar.bz2)
+
+    if [ ! -e "${buildroot}" ]; then
+        echo "Failed to find busybox archive, found : ${buildroot}" 1>&2
+        return 1
+    else
+        buildroot=$(basename $buildroot)
+    fi
+
+    rm -rf ${buildroot/.tar.bz2//}
+    tar xvjf ${ARTIFACTS}/${buildroot}
+    cd ${buildroot/.tar.bz2//}
+
+    cp $conf .config
+    if [ -n "$bbconf" ]; then
+        cp $bbconf package/busybox/
+    fi
+    make oldconfig
+    make
+
+    cp output/images/* $target
+}
+
+busybox_install "$1" "$2" "$3"
